//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceConsumer.PriceListService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ITMD466/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ITMD466/")]
    public partial class price : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIDField;
        
        private string locationCodeFromField;
        
        private string locationCodeToField;
        
        private string locationIDField;
        
        private string locationIDFromField;
        
        private string locationIDToField;
        
        private string price1Field;
        
        private string priceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string locationCodeFrom {
            get {
                return this.locationCodeFromField;
            }
            set {
                this.locationCodeFromField = value;
                this.RaisePropertyChanged("locationCodeFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string locationCodeTo {
            get {
                return this.locationCodeToField;
            }
            set {
                this.locationCodeToField = value;
                this.RaisePropertyChanged("locationCodeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string locationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
                this.RaisePropertyChanged("locationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string locationIDFrom {
            get {
                return this.locationIDFromField;
            }
            set {
                this.locationIDFromField = value;
                this.RaisePropertyChanged("locationIDFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string locationIDTo {
            get {
                return this.locationIDToField;
            }
            set {
                this.locationIDToField = value;
                this.RaisePropertyChanged("locationIDTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("price", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string price1 {
            get {
                return this.price1Field;
            }
            set {
                this.price1Field = value;
                this.RaisePropertyChanged("price1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string priceID {
            get {
                return this.priceIDField;
            }
            set {
                this.priceIDField = value;
                this.RaisePropertyChanged("priceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ITMD466/", ConfigurationName="PriceListService.PriceList")]
    public interface PriceList {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ITMD466/PriceList/listPricesRequest", ReplyAction="http://ITMD466/PriceList/listPricesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebServiceConsumer.PriceListService.Exception), Action="http://ITMD466/PriceList/listPrices/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServiceConsumer.PriceListService.listPricesResponse listPrices(WebServiceConsumer.PriceListService.listPricesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ITMD466/PriceList/listPricesRequest", ReplyAction="http://ITMD466/PriceList/listPricesResponse")]
        System.Threading.Tasks.Task<WebServiceConsumer.PriceListService.listPricesResponse> listPricesAsync(WebServiceConsumer.PriceListService.listPricesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listPrices", WrapperNamespace="http://ITMD466/", IsWrapped=true)]
    public partial class listPricesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ITMD466/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string priceID;
        
        public listPricesRequest() {
        }
        
        public listPricesRequest(string priceID) {
            this.priceID = priceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listPricesResponse", WrapperNamespace="http://ITMD466/", IsWrapped=true)]
    public partial class listPricesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ITMD466/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebServiceConsumer.PriceListService.price[] @return;
        
        public listPricesResponse() {
        }
        
        public listPricesResponse(WebServiceConsumer.PriceListService.price[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PriceListChannel : WebServiceConsumer.PriceListService.PriceList, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceListClient : System.ServiceModel.ClientBase<WebServiceConsumer.PriceListService.PriceList>, WebServiceConsumer.PriceListService.PriceList {
        
        public PriceListClient() {
        }
        
        public PriceListClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceListClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceListClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceListClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceConsumer.PriceListService.listPricesResponse WebServiceConsumer.PriceListService.PriceList.listPrices(WebServiceConsumer.PriceListService.listPricesRequest request) {
            return base.Channel.listPrices(request);
        }
        
        public WebServiceConsumer.PriceListService.price[] listPrices(string priceID) {
            WebServiceConsumer.PriceListService.listPricesRequest inValue = new WebServiceConsumer.PriceListService.listPricesRequest();
            inValue.priceID = priceID;
            WebServiceConsumer.PriceListService.listPricesResponse retVal = ((WebServiceConsumer.PriceListService.PriceList)(this)).listPrices(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceConsumer.PriceListService.listPricesResponse> WebServiceConsumer.PriceListService.PriceList.listPricesAsync(WebServiceConsumer.PriceListService.listPricesRequest request) {
            return base.Channel.listPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceConsumer.PriceListService.listPricesResponse> listPricesAsync(string priceID) {
            WebServiceConsumer.PriceListService.listPricesRequest inValue = new WebServiceConsumer.PriceListService.listPricesRequest();
            inValue.priceID = priceID;
            return ((WebServiceConsumer.PriceListService.PriceList)(this)).listPricesAsync(inValue);
        }
    }
}
